### PR TITLE
DM-37196: Update fields to reflect new APDB schema

### PR DESCRIPTION
**Pull request by parejkoj**

### CODE REVIEW

**Comment by kfindeisen** [comment]
Don't forget to run `make_preloaded_export.py` on any change to the `preloaded` contents. I'm surprised that local tests passed without it.

**Comment by parejkoj** [comment]
I don't think I'd need to run that: the SSO files changed in-place and have the same filenames, which come from running the `generate_ephemerides_gen3.py` script. There's nothing different for the export file to become aware of.

**Comment by kfindeisen** [comment]
I would expect the dataset IDs to have changed.

**Comment by parejkoj** [comment]
Oh, interesting. I just ran the script, and the uuids in the export.yaml did change for the updated SSO files (I did the same for cosmos_pdr2). Thanks for catching that: I had no idea that would be necessary. I did have successful runs of ap_verify with both this and cosmos_pdr2 without that export.yaml change, so I don't know who why that didn't break, unless the uuids there don't actually matter?

**Pull request merged**
